### PR TITLE
Authentication and node discovery improvements

### PR DESCRIPTION
**Pull request by gkawamoto**
We are using this project to manage our supervisors and made these improvements to the main engine of the cesi:
- Separation of the authentication engine, to implement other methods, such as GitHub based, SSH or LDAP (the last two are both pending).
- Separation of the node discovery engine, to implement other methods, such as external file and Docker API.
- Minor fixes, like enabling _enter_ on some forms, informing the configuration file through environment variable

### CODE REVIEW

**Comment by alexanderad** [comment]
Oh man, this looks great! We are looking for this feature to be merged as well, since we can then easily implement password-less login. Say `auth_mode = none`. You might ask who might want that? We have a case: we use cesi to manage multiple nodes in our environment and we have cesi running and available only inside of our internal network. We want all the developers to have same admin rights and no password authentication.

**Comment by GulsahKose** [comment]
Hi @gkawamoto, After merging that pull request, cesi was broken and i had to revert it. After i noticed that can be my fault. Thank you for your contributions. Your pull request includes extensive changes. I will create a new dev branch for that. When you have time, could you send a new pull request to dev branch?

**Comment by gkawamoto** [comment]
Sure @GulsahKose, to which branch should I send the new pull request?

**Comment by GulsahKose** [comment]
https://github.com/gamegos/cesi/tree/dev . Thanks a lot.

**Pull request merged**
